# Generated by Django 6.0.6 on 2026-07-29 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_interview'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='interview_mode',
            field=models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline')], default='ONLINE', max_length=20),
        ),
    ]
