# Generated by Django 6.0.6 on 2026-07-29 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_interview_interview_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='meeting_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
