# Generated by Django 6.0.6 on 2026-07-07 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0001_initial'),
        ('jobs', '0002_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParsedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleaned_text', models.TextField()),
                ('skills', models.JSONField(default=list)),
                ('education', models.JSONField(default=list)),
                ('experience', models.JSONField(default=dict)),
                ('parsed_at', models.DateTimeField(auto_now=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parsed_job', to='jobs.job')),
            ],
        ),
    ]
